server:
  port: 8085

spring:
  main:
    #解决bean重复定义的问题。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean
    allow-bean-definition-overriding: true
  profiles:
    active: yearomonth

#整合mybatis 的配置xxxxx
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyc.shardingjdbc.entity