server:
  port: 8085

spring:
  main:
    #解决bean重复定义的问题。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean
    allow-bean-definition-overriding: true
  #4.0 配置是shardingsphere 3.0是shardingjdbc
  shardingsphere:
    #参数配置，显示sql
    props:
      sql:
        show: true
    #配置数据源
    datasource:
      #给每个数据源取别名，下面的ds1,ds2,ds,ds3任意取名字
      names: ds1,ds2,ds3
      #给master-ds1每个数据源配置数据库连接信息
      ds1:
        #配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.23.10:3306/zyc_sharding_db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 111111
        maxPoolSize: 100
        minPoolSize: 5
      #配置ds2-slave
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.23.11:3306/zyc_sharding_db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 111111
        maxPoolSize: 100
        minPoolSize: 5
      #配置ds3-slave
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.23.11:3306/zyc_sharding_db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 111111
        maxPoolSize: 100
        minPoolSize: 5
    #配置默认数据源ds1; ***如果不设置新增的时候就会报错
    sharding:
      #配置数据源，主要用于写，注意一定要做读写分离,  注意：如果不配置， 那么就会把三个节点都当做从slave节点，新增，修改和删除都会报错
      default-data-source-name: ds1
    #配置数据源的读写分离，但是数据库一定要做主从复制
    masterslave:
       #配置主从名称，可以任意去名字
       name: ms
       #配置主库master， 负责数据的写入
       master-data-source-name: ds1
       #配置从库slave节点
       slave-data-source-names: ds2,ds3
       #配置slave节点的均衡策略，采用轮询机制 ；指针对从节点的读 默认是随机 random_robin
       load-balance-algorithm-type: round_robin
